import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarSlider from "@/components/Modal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
       {/*    <SidebarSlider />  aquí aparece el botón ☰ y el slider oculto */}
        
        {children}
      </body>
    </html>
  );
}
